-- TF-350: Inline comments on work item descriptions (GitHub-PR style)
--
-- Add a revision history for work_item descriptions and inline-anchor columns
-- on comments so a comment can reference a specific (line range, snippet)
-- inside a particular description revision. Comments without an anchor remain
-- regular comments — no behavioral change for them.

-- pgcrypto provides digest() / sha256, used here only for the back-fill below.
-- Application code computes sha256 in Go for new revisions.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE work_item_description_revisions (
    id              UUID PRIMARY KEY,
    work_item_id    UUID NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
    revision_number INT  NOT NULL,
    content         TEXT NOT NULL,
    content_hash    TEXT NOT NULL,
    author_id       UUID REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (work_item_id, revision_number)
);

CREATE INDEX idx_description_revisions_work_item
    ON work_item_description_revisions (work_item_id, created_at DESC);

-- Back-fill: every existing work item gets a single revision (number 1)
-- containing its current description. The revision id is a fresh v4 UUID
-- generated by the database. New revisions written by the application use
-- UUIDv7 (time-ordered). This is a one-shot back-fill; tests and runtime
-- rely on a stable created_at order, not on UUIDv7 vs v4.
INSERT INTO work_item_description_revisions
    (id, work_item_id, revision_number, content, content_hash, author_id, created_at)
SELECT
    gen_random_uuid(),
    wi.id,
    1,
    COALESCE(wi.description, ''),
    encode(digest(COALESCE(wi.description, ''), 'sha256'), 'hex'),
    wi.reporter_id,
    wi.created_at
FROM work_items wi
WHERE wi.deleted_at IS NULL;

-- Inline-comment anchor columns. anchor_revision_id IS NULL ⇒ regular comment.
ALTER TABLE comments
    ADD COLUMN anchor_revision_id   UUID REFERENCES work_item_description_revisions(id),
    ADD COLUMN anchor_start_line    INT,
    ADD COLUMN anchor_end_line      INT,
    ADD COLUMN anchor_snippet       TEXT,
    ADD COLUMN anchor_snippet_hash  TEXT,
    ADD COLUMN anchor_status        TEXT
        CHECK (anchor_status IS NULL OR anchor_status IN ('active', 'outdated'));

-- Help the re-anchor pass quickly find active inline comments for a work item.
CREATE INDEX idx_comments_anchor_active
    ON comments (work_item_id)
    WHERE anchor_status = 'active' AND deleted_at IS NULL;
