#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Taskwondo Setup Script
# =============================================================================
# Creates a .env file from .env.template, auto-generating secrets and
# prompting for user-defined values.
#
# Works in two modes:
#   Local:  when .env.template and docker-compose.yml exist in the target dir
#   Remote: downloads both files from GitHub (or a custom URL)

GITHUB_RAW_URL="https://raw.githubusercontent.com/marcoshack/taskwondo/main"
BASE_URL=""
TARGET_DIR="."
NON_INTERACTIVE=false
IMPORT_FILE=""

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Sets up Taskwondo by generating a .env file from the configuration template.

Options:
  --url URL        Base URL for downloading files
                   (default: $GITHUB_RAW_URL)
  --dir DIR        Target directory (default: current directory)
  --import FILE    Import data from a backup archive after setup
  -y               Non-interactive mode: auto-generate all values, skip prompts
  -h, --help       Show this help message
EOF
    exit 0
}

# --- Argument parsing ---

while [[ $# -gt 0 ]]; do
    case "$1" in
        --url)     BASE_URL="$2"; shift 2 ;;
        --dir)     TARGET_DIR="$2"; shift 2 ;;
        --import)  IMPORT_FILE="$2"; shift 2 ;;
        -y)        NON_INTERACTIVE=true; shift ;;
        -h|--help) usage ;;
        *)      echo "Unknown option: $1"; usage ;;
    esac
done

BASE_URL="${BASE_URL:-$GITHUB_RAW_URL}"

# --- Helpers ---

info()  { printf "\033[36m%s\033[0m\n" "$*"; }
ok()    { printf "\033[32m%s\033[0m\n" "$*"; }
warn()  { printf "\033[33m%s\033[0m\n" "$*" >&2; }
error() { printf "\033[31mError: %s\033[0m\n" "$*" >&2; exit 1; }

check_command() {
    if ! command -v "$1" &>/dev/null; then
        error "$1 is required but not found. Please install it first."
    fi
}

generate_hex_32() {
    openssl rand -hex 32
}

generate_password() {
    openssl rand -base64 24
}

# Prompt user for a value. Args: description, default_value
# In non-interactive mode, returns the default.
prompt_value() {
    local desc="$1"
    local default="$2"

    if $NON_INTERACTIVE; then
        echo "$default"
        return
    fi

    local prompt_text
    if [[ -n "$default" ]]; then
        prompt_text="  $desc [$default]: "
    else
        prompt_text="  $desc: "
    fi

    local value
    read -rp "$prompt_text" value </dev/tty
    echo "${value:-$default}"
}

download_file() {
    local url="$1"
    local dest="$2"

    if command -v curl &>/dev/null; then
        curl -fsSL "$url" -o "$dest"
    elif command -v wget &>/dev/null; then
        wget -q "$url" -O "$dest"
    else
        error "curl or wget is required to download files."
    fi
}

# --- Preflight checks ---

info "Checking prerequisites..."

check_command openssl
check_command docker

if ! docker compose version &>/dev/null; then
    error "docker compose (v2) is required but not found. Install Docker Compose v2."
fi

printf "  openssl:         %s\n" "$(openssl version 2>&1 | head -1)"
printf "  docker:          %s\n" "$(docker --version 2>&1)"
printf "  docker compose:  %s\n" "$(docker compose version 2>&1)"
echo

# --- Ensure target directory exists ---

mkdir -p "$TARGET_DIR"

# --- Determine mode: local or remote ---

TEMPLATE_FILE="$TARGET_DIR/.env.template"
COMPOSE_FILE="$TARGET_DIR/docker-compose.yml"

if [[ -f "$TEMPLATE_FILE" && -f "$COMPOSE_FILE" ]]; then
    info "Local mode: using files from $TARGET_DIR"
else
    info "Remote mode: downloading files from $BASE_URL"

    if [[ ! -f "$TEMPLATE_FILE" ]]; then
        info "  Downloading .env.template..."
        download_file "$BASE_URL/.env.template" "$TEMPLATE_FILE"
    fi

    if [[ ! -f "$COMPOSE_FILE" ]]; then
        info "  Downloading docker-compose.yml..."
        download_file "$BASE_URL/docker-compose.yml" "$COMPOSE_FILE"
    fi

    ok "  Files downloaded."
    echo
fi

# --- Check for existing .env ---

ENV_FILE="$TARGET_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    if $NON_INTERACTIVE; then
        warn ".env already exists, overwriting (non-interactive mode)."
    else
        read -rp "$(warn '.env already exists. Overwrite? [y/N] ')" confirm </dev/tty
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            info "Aborted. Existing .env was not modified."
            exit 0
        fi
    fi
fi

# --- Parse template and generate .env ---

info "Generating .env..."
echo

# Associative array to store generated values (for __COPY__ and __DERIVE__)
declare -A vars
output="# Taskwondo Configuration"$'\n'
output+="# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"$'\n'
in_header=true

while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip the template header block (top comments before first blank line)
    if $in_header; then
        if [[ -z "$line" ]]; then
            in_header=false
            output+=$'\n'
        fi
        continue
    fi

    # Skip comment lines that document template markers
    if [[ "$line" =~ ^#.*__ ]]; then
        continue
    fi

    # Blank lines and comments: pass through
    if [[ -z "$line" || "$line" =~ ^# ]]; then
        output+="$line"$'\n'
        continue
    fi

    # Split KEY=VALUE
    if [[ "$line" =~ ^([A-Z_][A-Z0-9_]*)=(.*) ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"
    else
        # Not a KEY=VALUE line, pass through
        output+="$line"$'\n'
        continue
    fi

    # Process marker values
    case "$value" in
        __GENERATE_HEX_32__)
            value="$(generate_hex_32)"
            ;;
        __GENERATE_PASSWORD__)
            value="$(generate_password)"
            ;;
        __PROMPT:*__)
            # Extract description and optional default from __PROMPT:desc [default]__
            local_desc="${value#__PROMPT:}"
            local_desc="${local_desc%__}"
            local_default=""
            if [[ "$local_desc" =~ \[([^]]*)\]$ ]]; then
                local_default="${BASH_REMATCH[1]}"
                local_desc="${local_desc% \[*\]}"
            fi
            value="$(prompt_value "$local_desc" "$local_default")"
            ;;
        __COPY:*__)
            # Copy value from another variable
            local_ref="${value#__COPY:}"
            local_ref="${local_ref%__}"
            value="${vars[$local_ref]:-}"
            ;;
        __DERIVE:*__)
            # Evaluate shell expression with current vars
            local_expr="${value#__DERIVE:}"
            local_expr="${local_expr%__}"
            # Substitute ${VAR} references with actual values
            for var_name in "${!vars[@]}"; do
                local_expr="${local_expr//\$\{$var_name\}/${vars[$var_name]}}"
            done
            value="$local_expr"
            ;;
        __OPTIONAL__)
            value=""
            ;;
        # Default: keep value as-is
    esac

    vars["$key"]="$value"
    output+="$key=$value"$'\n'

done < "$TEMPLATE_FILE"

# --- Write .env ---

printf '%s' "$output" > "$ENV_FILE"

# --- Summary ---

echo
ok "=== Taskwondo Setup Complete ==="
echo
printf "  Web UI:  http://localhost:%s\n" "${vars[WEB_PORT]:-3000}"
printf "  API:     http://localhost:%s\n" "${vars[API_PORT]:-8080}"
echo

# --- Import from backup ---

if [[ -n "$IMPORT_FILE" ]]; then
    if [[ ! -f "$IMPORT_FILE" ]]; then
        error "Import file not found: $IMPORT_FILE"
    fi

    info "Importing data from: $IMPORT_FILE"
    echo

    # Copy import file to backups directory.
    mkdir -p "$TARGET_DIR/backups"
    cp "$IMPORT_FILE" "$TARGET_DIR/backups/taskwondo-import.tar.gz"

    # Start database and storage services.
    info "Starting database and storage services..."
    cd "$TARGET_DIR"
    docker compose -f docker-compose.yml up -d postgres minio minio-init

    info "Waiting for services to be healthy..."
    local_attempts=0
    while ! docker compose -f docker-compose.yml exec -T postgres pg_isready -U "${vars[POSTGRES_USER]:-taskwondo}" &>/dev/null; do
        local_attempts=$((local_attempts + 1))
        if [[ $local_attempts -ge 30 ]]; then
            error "Timed out waiting for database to be ready."
        fi
        sleep 1
    done

    # Run import.
    info "Running import..."
    IMPORT_FILE=taskwondo-import.tar.gz docker compose -f docker-compose.yml run --rm import

    # Start all services.
    info "Starting all services..."
    docker compose -f docker-compose.yml up -d

    echo
    ok "=== Taskwondo restored from backup and running ==="
    echo
    printf "  Web UI:  http://localhost:%s\n" "${vars[WEB_PORT]:-3000}"
    printf "  API:     http://localhost:%s\n" "${vars[API_PORT]:-8080}"
    echo
else
    printf "  Admin email:     %s\n" "${vars[ADMIN_EMAIL]:-not set}"
    printf "  Admin password:  %s\n" "${vars[ADMIN_PASSWORD]:-not set}"
    echo
    info "To start Taskwondo:"
    echo "  docker compose -f docker-compose.yml up -d"
    echo
    info "The API will automatically run database migrations and"
    info "seed the admin user on first start."
    echo
fi
